<select id="country" name="country" class="form-select">
    <option value="AF">Afganistāna</option>
    <option value="AX">Alandu salas</option>
    <option value="AL">Albānija</option>
    <option value="DZ">Alžīrija</option>
    <option value="AS">amerikāņu Samoa</option>
    <option value="AD">Andora</option>
    <option value="AO">Angola</option>
    <option value="AI">Angilja</option>
    <option value="AQ">Antarktīda</option>
    <option value="AG">Antigva un Barbuda</option>
    <option value="AR">Argentīna</option>
    <option value="AM">Armēnija</option>
    <option value="AW">Aruba</option>
    <option value="AU">Austrālija</option>
    <option value="AT">Austrija</option>
    <option value="AZ">Azerbaidžāna</option>
    <option value="BS">Bahamu salas</option>
    <option value="BH">Bahreina</option>
    <option value="BD">Bangladeša</option>
    <option value="BB">Barbadosa</option>
    <option value="BY">Baltkrievija</option>
    <option value="BE">Beļģija</option>
    <option value="BZ">Beliza</option>
    <option value="BJ">Benina</option>
    <option value="BM">Bermudu salas</option>
    <option value="BT">Butāna</option>
    <option value="BO">Bolīvija</option>
    <option value="BQ">Bonaire, Sint Eustatius un Saba</option>
    <option value="BA">Bosnija un Hercegovina</option>
    <option value="BW">Botsvāna</option>
    <option value="BV">Bouvet sala</option>
    <option value="BR">Brazīlija</option>
    <option value="IO">Indijas okeāna Britu teritorija</option>
    <option value="BN">Bruneja Darusalama</option>
    <option value="BG">Bulgārija</option>
    <option value="BF">Burkinafaso</option>
    <option value="BI">Burundi</option>
    <option value="KH">Kambodža</option>
    <option value="CM">Kamerūna</option>
    <option value="CA">Kanāda</option>
    <option value="CV">Kaboverde</option>
    <option value="KY">Kaimanu salas</option>
    <option value="CF">Centrālāfrikas Republika</option>
    <option value="TD">Čada</option>
    <option value="CL">Čīle</option>
    <option value="CN">Ķīna</option>
    <option value="CX">Ziemassvētku sala</option>
    <option value="CC">Kokosa (Kīlinga) salas</option>
    <option value="CO">Kolumbija</option>
    <option value="KM">Komoru salas</option>
    <option value="CG">Kongo</option>
    <option value="CD">Kongo, Kongo Demokrātiskā Republika</option>
    <option value="CK">Kuka salas</option>
    <option value="CR">Kostarika</option>
    <option value="CI">Kotdivuāra</option>
    <option value="HR">Horvātija</option>
    <option value="CU">Kuba</option>
    <option value="CW">Kirasao</option>
    <option value="CY">Kipra</option>
    <option value="CZ">Čehu Republika</option>
    <option value="DK">Dānija</option>
    <option value="DJ">Džibutija</option>
    <option value="DM">Dominika</option>
    <option value="DO">Dominikānas republika</option>
    <option value="EC">Ekvadora</option>
    <option value="EG">Ēģipte</option>
    <option value="SV">Salvadora</option>
    <option value="GQ">Ekvatoriālā Gvineja</option>
    <option value="ER">Eritreja</option>
    <option value="EE">Igaunija</option>
    <option value="ET">Etiopija</option>
    <option value="FK">Folklendas salas (Malvinas)</option>
    <option value="FO">Farēru salas</option>
    <option value="FJ">Fidži</option>
    <option value="FI">Somija</option>
    <option value="FR">Francija</option>
    <option value="GF">Franču Gviāna</option>
    <option value="PF">Franču Polinēzija</option>
    <option value="TF">Francijas dienvidu teritorijas</option>
    <option value="GA">Gabona</option>
    <option value="GM">Gambija</option>
    <option value="GE">Džordžija</option>
    <option value="DE">Vācija</option>
    <option value="GH">Gana</option>
    <option value="GI">Gibraltārs</option>
    <option value="GR">Grieķija</option>
    <option value="GL">Grenlande</option>
    <option value="GD">Grenāda</option>
    <option value="GP">Gvadelupa</option>
    <option value="GU">Guama</option>
    <option value="GT">Gvatemala</option>
    <option value="GG">Gērnsija</option>
    <option value="GN">Gvineja</option>
    <option value="GW">Gvineja-Bisava</option>
    <option value="GY">Gajāna</option>
    <option value="HT">Haiti</option>
    <option value="HM">Hērda un Makdonalda salas</option>
    <option value="VA">Svētais Krēsls (Vatikāna Pilsētvalsts)</option>
    <option value="HN">Hondurasa</option>
    <option value="HK">Honkonga</option>
    <option value="HU">Ungārija</option>
    <option value="IS">Islande</option>
    <option value="IN">Indija</option>
    <option value="ID">Indonēzija</option>
    <option value="IR">Irāna, Islāma Republika</option>
    <option value="IQ">Irāka</option>
    <option value="IE">Īrija</option>
    <option value="IM">cilvēka sala</option>
    <option value="IL">Izraēla</option>
    <option value="IT">Itālija</option>
    <option value="JM">Jamaika</option>
    <option value="JP">Japāna</option>
    <option value="JE">Džērsija</option>
    <option value="JO">Džordana</option>
    <option value="KZ">Kazahstāna</option>
    <option value="KE">Kenija</option>
    <option value="KI">Kiribati</option>
    <option value="KP">Korejas Tautas Demokrātiskā Republika</option>
    <option value="KR">Korejas Republika</option>
    <option value="XK">Kosova</option>
    <option value="KW">Kuveita</option>
    <option value="KG">Kirgizstāna</option>
    <option value="LA">Laosas Tautas Demokrātiskā Republika</option>
    <option value="LV" selected="">Latvija</option>
    <option value="LB">Libāna</option>
    <option value="LS">Lesoto</option>
    <option value="LR">Libērija</option>
    <option value="LY">Lībijas arābu Džamahirija</option>
    <option value="LI">Lihtenšteina</option>
    <option value="LT">Lietuva</option>
    <option value="LU">Luksemburga</option>
    <option value="MO">Makao</option>
    <option value="MK">Maķedonija, Bijusī Dienvidslāvijas Republika</option>
    <option value="MG">Madagaskara</option>
    <option value="MW">Malāvija</option>
    <option value="MY">Malaizija</option>
    <option value="MV">Maldīvija</option>
    <option value="ML">Mali</option>
    <option value="MT">Malta</option>
    <option value="MH">Māršala salas</option>
    <option value="MQ">Martinika</option>
    <option value="MR">Mauritānija</option>
    <option value="MU">Maurīcija</option>
    <option value="YT">Majota</option>
    <option value="MX">Meksika</option>
    <option value="FM">Mikronēzija, Mikronēzijas Federatīvās Valstis</option>
    <option value="MD">Moldovas Republika</option>
    <option value="MC">Monako</option>
    <option value="MN">Mongolija</option>
    <option value="ME">Melnkalne</option>
    <option value="MS">Monserata</option>
    <option value="MA">Maroka</option>
    <option value="MZ">Mozambika</option>
    <option value="MM">Mjanma</option>
    <option value="NA">Namībija</option>
    <option value="NR">Nauru</option>
    <option value="NP">Nepāla</option>
    <option value="NL">Nīderlande</option>
    <option value="AN">Nīderlandes Antiļas</option>
    <option value="NC">Jaunkaledonija</option>
    <option value="NZ">Jaunzēlande</option>
    <option value="NI">Nikaragva</option>
    <option value="NE">Nigēra</option>
    <option value="NG">Nigērija</option>
    <option value="NU">Niue</option>
    <option value="NF">Norfolkas sala</option>
    <option value="MP">Marianas ziemeļu salas</option>
    <option value="NO">Norvēģija</option>
    <option value="OM">Omāna</option>
    <option value="PK">Pakistāna</option>
    <option value="PW">Palau</option>
    <option value="PS">Palestīnas teritorija, okupēta</option>
    <option value="PA">Panama</option>
    <option value="PG">Papua Jaungvineja</option>
    <option value="PY">Paragvaja</option>
    <option value="PE">Peru</option>
    <option value="PH">Filipīnas</option>
    <option value="PN">Pitkērna</option>
    <option value="PL">Polija</option>
    <option value="PT">Portugāle</option>
    <option value="PR">Puertoriko</option>
    <option value="QA">Katara</option>
    <option value="RE">Atkalapvienošanās</option>
    <option value="RO">Rumānija</option>
    <option value="RU">Krievijas Federācija</option>
    <option value="RW">Ruanda</option>
    <option value="BL">Svētā Bartelemija</option>
    <option value="SH">Svētā Helēna</option>
    <option value="KN">Sentkitsa un Nevisa</option>
    <option value="LC">Sentlūsija</option>
    <option value="MF">Svētais Mārtiņš</option>
    <option value="PM">Senpjēra un Mikelona</option>
    <option value="VC">Sentvinsenta un Grenadīnas</option>
    <option value="WS">Samoa</option>
    <option value="SM">Sanmarīno</option>
    <option value="ST">Santome un Prinsipi</option>
    <option value="SA">Saūda Arābija</option>
    <option value="SN">Senegāla</option>
    <option value="RS">Serbija</option>
    <option value="CS">Serbija un Melnkalne</option>
    <option value="SC">Seišelu salas</option>
    <option value="SL">Sjerraleone</option>
    <option value="SG">Singapūra</option>
    <option value="SX">Sv. Mārtiņš</option>
    <option value="SK">Slovākija</option>
    <option value="SI">Slovēnija</option>
    <option value="SB">Zālamana salas</option>
    <option value="SO">Somālija</option>
    <option value="ZA">Dienvidāfrika</option>
    <option value="GS">Dienviddžordžija un Dienvidsendviču salas</option>
    <option value="SS">Dienvidsudāna</option>
    <option value="ES">Spānija</option>
    <option value="LK">Šrilanka</option>
    <option value="SD">Sudāna</option>
    <option value="SR">Surinama</option>
    <option value="SJ">Svalbārs un Jans Majens</option>
    <option value="SZ">Svazilenda</option>
    <option value="SE">Zviedrija</option>
    <option value="CH">Šveice</option>
    <option value="SY">Sīrijas Arābu Republika</option>
    <option value="TW">Taivāna, Ķīnas province</option>
    <option value="TJ">Tadžikistāna</option>
    <option value="TZ">Tanzānijas Apvienotā Republika</option>
    <option value="TH">Taizeme</option>
    <option value="TL">Austrumtimora</option>
    <option value="TG">Iet</option>
    <option value="TK">Tokelau</option>
    <option value="TO">Tonga</option>
    <option value="TT">Trinidada un Tobāgo</option>
    <option value="TN">Tunisija</option>
    <option value="TR">Turcija</option>
    <option value="TM">Turkmenistāna</option>
    <option value="TC">Tērksas un Kaikosas salas</option>
    <option value="TV">Tuvalu</option>
    <option value="UG">Uganda</option>
    <option value="UA">Ukraina</option>
    <option value="AE">Apvienotie Arābu Emirāti</option>
    <option value="GB">Apvienotā Karaliste</option>
    <option value="US">Savienotās Valstis</option>
    <option value="UM">Amerikas Savienoto Valstu mazās nomaļās salas</option>
    <option value="UY">Urugvaja</option>
    <option value="UZ">Uzbekistāna</option>
    <option value="VU">Vanuatu</option>
    <option value="VE">Venecuēla</option>
    <option value="VN">Vjetnama</option>
    <option value="VG">Virdžīnu salas, Lielbritānijas</option>
    <option value="VI">Virdžīnu salas, ASV</option>
    <option value="WF">Voliss un Futuna</option>
    <option value="EH">Rietumsahāra</option>
    <option value="YE">Jemena</option>
    <option value="ZM">Zambija</option>
    <option value="ZW">Zimbabve</option>
</select>
